# Generated by Django 4.2.4 on 2023-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
